/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Masajista;
import Persistencia.Conexion;
import Persistencia.MasajistaData;
import javax.swing.JOptionPane;

/**
 *
 * @author vanne
 */
public class GestiondeMasajistas extends javax.swing.JInternalFrame {

    private Conexion conexion;

    public GestiondeMasajistas(Conexion conexion) {
        initComponents();
        this.conexion = conexion;
        cargarMasajistasActivos();
        jbNuevoActionPerformed(null);
    }

    public void centrarEnDesktop(javax.swing.JDesktopPane desktopPane) {
        int x = (desktopPane.getWidth() - this.getWidth()) / 2;
        int y = (desktopPane.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    private void cargarMasajistasActivos() {
        try {
            MasajistaData md = new MasajistaData(conexion);
            java.util.List<Masajista> lista = md.listarMasajistasActivos();

            jComboBox1.removeAllItems(); // limpia el combo

            for (Masajista m : lista) {
                jComboBox1.addItem(m);
            }

            jComboBox1.setSelectedIndex(-1); // sin selección inicial
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar masajistas activos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jGestionDeMasajista = new javax.swing.JLabel();
        jCodigoMasajista = new javax.swing.JLabel();
        jNombreCompleto = new javax.swing.JLabel();
        jEspecialidad = new javax.swing.JLabel();
        jTelefono = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jcbActivo = new javax.swing.JCheckBox();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jcbEspecialidad = new javax.swing.JComboBox<>();
        jTelefono1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        jGestionDeMasajista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jGestionDeMasajista.setForeground(new java.awt.Color(153, 0, 204));
        jGestionDeMasajista.setText("Gestion de Masajistas");

        jCodigoMasajista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCodigoMasajista.setText("Matricula");

        jNombreCompleto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jNombreCompleto.setText("Nombre Completo :");

        jEspecialidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jEspecialidad.setText("Especialidad : ");

        jTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTelefono.setText("Telefono :");

        jcbActivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbActivo.setText("Activo");

        jbNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jcbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facial", "Corporal", "Relajacion", "Estetico" }));
        jcbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspecialidadActionPerformed(evt);
            }
        });

        jTelefono1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTelefono1.setText("Masajistas activos");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jGestionDeMasajista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCodigoMasajista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jNombreCompleto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jEspecialidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbActivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbEspecialidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTelefono1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jGestionDeMasajista))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jNombreCompleto)
                                    .addComponent(jCodigoMasajista)
                                    .addComponent(jEspecialidad)
                                    .addComponent(jTelefono)
                                    .addComponent(jTelefono1))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jcbActivo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jtfMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                                        .addComponent(jtfNombre))
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(jtfTelefono))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGestionDeMasajista)
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoMasajista)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombreCompleto)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEspecialidad)
                    .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefono)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefono1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Masajista masajistaActual;

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        try {
            // define regex para validar telefono de 10 digitos y nombre solo con letras y espacios
            String regexTelefono = "^[0-9]{10}$";
            String regexNombre = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$";

            // obtiene los datos ingresados
            String nombre = jtfNombre.getText();
            String textoTelefono = jtfTelefono.getText();
            String especialidad = (String) jcbEspecialidad.getSelectedItem();
            boolean estado = jcbActivo.isSelected();

            // valida campos obligatorios
            if (nombre.isEmpty() || textoTelefono.isEmpty() || especialidad == null) {
                JOptionPane.showMessageDialog(this, "debes rellenar todos los campos obligatorios", "campos vacios", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // valida formato del nombre
            if (!nombre.matches(regexNombre)) {
                JOptionPane.showMessageDialog(this, "el nombre solo puede contener letras y espacios", "error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // valida formato y largo del telefono
            if (!textoTelefono.matches(regexTelefono)) {
                JOptionPane.showMessageDialog(this, "telefono debe tener exactamente 10 numeros", "error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // convierte el telefono a tipo long
            long telefono = Long.parseLong(textoTelefono);

            // crea el masajista y lo guarda en la base de datos
            Masajista m = new Masajista(nombre, String.valueOf(telefono), especialidad, estado);
            MasajistaData md = new MasajistaData(conexion);
            md.guardarMasajista(m);

            // muestra mensaje de exito
            JOptionPane.showMessageDialog(this, "masajista guardado correctamente");

            // limpia los campos del formulario
            jtfNombre.setText("");
            jtfTelefono.setText("");
            jcbEspecialidad.setSelectedIndex(-1);
            jcbActivo.setSelected(false);
            cargarMasajistasActivos();

        } catch (Exception e) {
            // captura cualquier error y lo muestra
            JOptionPane.showMessageDialog(this, "ocurrio un error: " + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        try {
            String matricula = jtfMatricula.getText().trim();

            if (matricula.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes ingresar la matrícula del masajista", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                return;
            }

            MasajistaData md = new MasajistaData(conexion);
            Masajista m = md.buscarMasajista(matricula);

            if (m != null) {
                masajistaActual = m;
                jtfNombre.setText(m.getNombreYApellido());
                jtfTelefono.setText(m.getTelefono());
                for (int i = 0; i < jcbEspecialidad.getItemCount(); i++) {
                    String item = jcbEspecialidad.getItemAt(i).toString().trim();
                    if (item.equalsIgnoreCase(m.getEspecialidad().trim())) {
                        jcbEspecialidad.setSelectedIndex(i);
                        break;
                    }
                }

                jcbActivo.setSelected(m.isEstado());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún masajista con esa matrícula", "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar masajista: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            // define regex para validar telefono de 10 digitos y nombre solo con letras y espacios
            String regexTelefono = "^[0-9]{10}$";
            String regexNombre = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$";

            // valida que haya un masajista cargado
            if (masajistaActual == null) {
                JOptionPane.showMessageDialog(this, "debes buscar un masajista antes de modificarlo", "error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // obtiene los datos ingresados
            String matricula = jtfMatricula.getText().trim();
            String nombre = jtfNombre.getText().trim();
            String telefono = jtfTelefono.getText().trim();
            String especialidad = (String) jcbEspecialidad.getSelectedItem();
            boolean estado = jcbActivo.isSelected();

            // valida que los campos obligatorios no esten vacios
            if (matricula.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || especialidad == null || especialidad.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "debes rellenar todos los campos obligatorios", "campos vacios", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // valida formato del nombre
            if (!nombre.matches(regexNombre)) {
                JOptionPane.showMessageDialog(this, "el nombre solo puede contener letras y espacios", "error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // valida formato y largo del telefono
            if (!telefono.matches(regexTelefono)) {
                JOptionPane.showMessageDialog(this, "telefono debe tener exactamente 10 numeros", "error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // actualiza los datos del masajista
            masajistaActual.setMatricula(matricula);
            masajistaActual.setNombreYApellido(nombre);
            masajistaActual.setTelefono(telefono);
            masajistaActual.setEspecialidad(especialidad);
            masajistaActual.setEstado(estado);

            // guarda los cambios en la base de datos
            MasajistaData md = new MasajistaData(conexion);
            md.actualizarMasajista(masajistaActual);

            // muestra mensaje de exito
            JOptionPane.showMessageDialog(this, "masajista actualizado correctamente");

            // limpia los campos del formulario
            jtfMatricula.setText("");
            jtfNombre.setText("");
            jtfTelefono.setText("");
            jcbEspecialidad.setSelectedIndex(-1);
            jcbActivo.setSelected(false);
            masajistaActual = null;
            cargarMasajistasActivos();

        } catch (Exception e) {
            // captura cualquier error y lo muestra
            JOptionPane.showMessageDialog(this, "ocurrio un error: " + e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtfMatricula.setText("");
        jtfNombre.setText("");
        jtfTelefono.setText("");
        jcbEspecialidad.setSelectedIndex(0);
        jcbActivo.setSelected(false);
        masajistaActual = null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jcbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEspecialidadActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Masajista seleccionado = (Masajista) jComboBox1.getSelectedItem();
        if (seleccionado != null) {
            masajistaActual = seleccionado;
            jtfMatricula.setText(seleccionado.getMatricula());
            jtfNombre.setText(seleccionado.getNombreYApellido());
            jtfTelefono.setText(seleccionado.getTelefono());
            for (int i = 0; i < jcbEspecialidad.getItemCount(); i++) {
                String item = jcbEspecialidad.getItemAt(i).toString().trim();
                if (item.equalsIgnoreCase(seleccionado.getEspecialidad().trim())) {
                    jcbEspecialidad.setSelectedIndex(i);
                    break;
                }
            }

            jcbActivo.setSelected(seleccionado.isEstado());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCodigoMasajista;
    private javax.swing.JComboBox<Masajista> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jEspecialidad;
    private javax.swing.JLabel jGestionDeMasajista;
    private javax.swing.JLabel jNombreCompleto;
    private javax.swing.JLabel jTelefono;
    private javax.swing.JLabel jTelefono1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JComboBox<String> jcbEspecialidad;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
