/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Instalacion;
import Persistencia.InstalacionData;
import javax.swing.JOptionPane;
import Persistencia.Conexion;

/**
 *
 * @author vanne
 */
public class GestiondeInstalaciones extends javax.swing.JInternalFrame {

    private Conexion conexion;
    private Instalacion instalacionActual;
    private InstalacionData instalacionData;

    /**
     * Creates new form GestiondeInstalaciones
     */
    public GestiondeInstalaciones(Conexion conexion) {
        initComponents();
        this.conexion = conexion;
        this.instalacionData = new InstalacionData(conexion);
        cargarInstalacionesActivas();
        jbNuevoActionPerformed(null);
    }
public void centrarEnDesktop(javax.swing.JDesktopPane desktopPane) {
        int x = (desktopPane.getWidth() - this.getWidth()) / 2;
        int y = (desktopPane.getHeight() - this.getHeight()) / 2;
        this.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jGestioDeInstalacion = new javax.swing.JLabel();
        jCodigoInstalacion = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jTipo = new javax.swing.JLabel();
        jCapacidad = new javax.swing.JLabel();
        jtfCodigoInstalacion = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfCapacidad = new javax.swing.JTextField();
        jcbActivo = new javax.swing.JCheckBox();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jtfPrecio = new javax.swing.JTextField();
        jCapacidad1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        jGestioDeInstalacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jGestioDeInstalacion.setForeground(new java.awt.Color(153, 0, 153));
        jGestioDeInstalacion.setText("Gestión de Instalaciones");

        jCodigoInstalacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCodigoInstalacion.setText("Codigo instalacion :");

        jNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jNombre.setText("Nombre :  ");

        jTipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTipo.setText("Precio :");

        jCapacidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCapacidad.setText("Detalles de uso:");

        jcbActivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jcbActivo.setText("Activo");

        jbNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153)));
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153)));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 153)));
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jCapacidad1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCapacidad1.setText("Instalaciones activas");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jGestioDeInstalacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCodigoInstalacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfCodigoInstalacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbActivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCapacidad1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 143, Short.MAX_VALUE)
                .addComponent(jGestioDeInstalacion)
                .addGap(144, 144, 144))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCodigoInstalacion)
                            .addComponent(jNombre)
                            .addComponent(jTipo)
                            .addComponent(jCapacidad)
                            .addComponent(jCapacidad1))
                        .addGap(42, 42, 42)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbActivo)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jtfCodigoInstalacion)
                                        .addComponent(jtfCapacidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                                .addContainerGap(116, Short.MAX_VALUE))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jGestioDeInstalacion)
                .addGap(42, 42, 42)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoInstalacion)
                    .addComponent(jtfCodigoInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipo)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCapacidad)
                    .addComponent(jtfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCapacidad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarInstalacionesActivas() {
        try {
            InstalacionData id = new InstalacionData(conexion);
            java.util.List<Instalacion> instalaciones = id.listarInstalacionesActivas();

            jComboBox1.removeAllItems();

            for (Instalacion i : instalaciones) {
                jComboBox1.addItem(i);
            }

            jComboBox1.setSelectedIndex(-1); // sin selección inicial
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar instalaciones activas: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtfCodigoInstalacion.setText("");
        jtfNombre.setText("");
        jtfPrecio.setText("");
        jtfCapacidad.setText("");
        jcbActivo.setSelected(false);
        instalacionActual = null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        try {
            String nombre = jtfNombre.getText().trim();
            String detalle = jtfCapacidad.getText().trim();
            String precioTxt = jtfPrecio.getText().trim();
            boolean activo = jcbActivo.isSelected();

            if (nombre.isEmpty() || detalle.isEmpty() || precioTxt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes completar todos los campos obligatorios", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double precio = Double.parseDouble(precioTxt);

            Instalacion nueva = new Instalacion(nombre, detalle, precio, activo);
            InstalacionData id = new InstalacionData(conexion);
            id.guardarInstalacion(nueva);

            instalacionActual = nueva;
            jtfCodigoInstalacion.setText(String.valueOf(nueva.getCodInstal()));

            JOptionPane.showMessageDialog(this, "Instalación guardada correctamente");
            cargarInstalacionesActivas();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar la instalación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            if (instalacionActual == null) {
                JOptionPane.showMessageDialog(this, "Primero debes buscar una instalación", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String nombre = jtfNombre.getText().trim();
            String detalle = jtfCapacidad.getText().trim();
            String precioTxt = jtfPrecio.getText().trim();
            boolean activo = jcbActivo.isSelected();

            if (nombre.isEmpty() || detalle.isEmpty() || precioTxt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes completar todos los campos obligatorios", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double precio = Double.parseDouble(precioTxt);

            instalacionActual.setNombre(nombre);
            instalacionActual.setdetalle_de_uso(detalle);
            instalacionActual.setPrecio30m(precio);
            instalacionActual.setEstado(activo);

            InstalacionData id = new InstalacionData(conexion);
            id.actualizarInstalacion(instalacionActual);

            JOptionPane.showMessageDialog(this, "Instalación modificada correctamente");
            cargarInstalacionesActivas();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar la instalación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        try {
            String codigoTxt = jtfCodigoInstalacion.getText().trim();
            if (codigoTxt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes ingresar un código de instalación para buscar", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int codigo = Integer.parseInt(codigoTxt);
            InstalacionData id = new InstalacionData(conexion);
            Instalacion encontrada = id.buscarInstalacion(codigo);

            if (encontrada != null) {
                instalacionActual = encontrada;
                jtfNombre.setText(encontrada.getNombre());
                jtfCapacidad.setText(encontrada.getdetalle_de_uso());
                jtfPrecio.setText(String.valueOf(encontrada.getPrecio30m()));
                jcbActivo.setSelected(encontrada.isEstado());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna instalación con ese código", "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar la instalación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Instalacion seleccionada = (Instalacion) jComboBox1.getSelectedItem();
        if (seleccionada != null) {
            instalacionActual = seleccionada;
            jtfCodigoInstalacion.setText(String.valueOf(seleccionada.getCodInstal()));
            jtfNombre.setText(seleccionada.getNombre());
            jtfCapacidad.setText(seleccionada.getdetalle_de_uso());
            jtfPrecio.setText(String.valueOf(seleccionada.getPrecio30m()));
            jcbActivo.setSelected(seleccionada.isEstado());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCapacidad;
    private javax.swing.JLabel jCapacidad1;
    private javax.swing.JLabel jCodigoInstalacion;
    private javax.swing.JComboBox<Instalacion> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jGestioDeInstalacion;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jTipo;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JCheckBox jcbActivo;
    private javax.swing.JTextField jtfCapacidad;
    private javax.swing.JTextField jtfCodigoInstalacion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPrecio;
    // End of variables declaration//GEN-END:variables
}
