/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Consultorio;
import Persistencia.Conexion;
import Persistencia.ConsultorioData;
import javax.swing.JOptionPane;

/**
 *
 * @author vanne
 */
public class GestionConsultorios extends javax.swing.JInternalFrame {

    private Conexion conexion;
    private Consultorio consultorioActual;

    /**
     * Creates new form GestionConsultorios
     */
    public GestionConsultorios(Conexion conexion) {
        initComponents();
        this.conexion = conexion;
        cargarConsultoriosActivos();
        jbNuevoActionPerformed(null);
    }

    private void cargarConsultoriosActivos() {
        try {
            ConsultorioData cd = new ConsultorioData(conexion);
            java.util.List<Consultorio> lista = cd.listarConsultoriosAptos();

            jcbConsultoriosActivos.removeAllItems(); // limpia combo

            for (Consultorio c : lista) {
                jcbConsultoriosActivos.addItem(c);
            }

            jcbConsultoriosActivos.setSelectedIndex(-1); // sin selección inicial
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar consultorios activos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jGestionDeConsultorio = new javax.swing.JLabel();
        jCodigoConsultorio = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jCapacidad = new javax.swing.JLabel();
        jtfCodigoConsultorio = new javax.swing.JTextField();
        jtfUsos = new javax.swing.JTextField();
        jtfCapacidad = new javax.swing.JTextField();
        jcbApto = new javax.swing.JCheckBox();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jCapacidad1 = new javax.swing.JLabel();
        jcbConsultoriosActivos = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        jGestionDeConsultorio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jGestionDeConsultorio.setForeground(new java.awt.Color(153, 0, 204));
        jGestionDeConsultorio.setText("Gestión de Consultorios");

        jCodigoConsultorio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCodigoConsultorio.setText("Codigo consultorio:");

        jNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jNombre.setText("Usos:");

        jCapacidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCapacidad.setText("Equipamiento:");

        jcbApto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbApto.setText("Apto");
        jcbApto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAptoActionPerformed(evt);
            }
        });

        jbNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204)));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jCapacidad1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCapacidad1.setText("Consultorios activos");

        jcbConsultoriosActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConsultoriosActivosActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jGestionDeConsultorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCodigoConsultorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfCodigoConsultorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfUsos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfCapacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbApto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCapacidad1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbConsultoriosActivos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jcbApto))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jCapacidad1)
                                .addGap(44, 44, 44)
                                .addComponent(jcbConsultoriosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCapacidad)
                                    .addComponent(jNombre)
                                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jCodigoConsultorio)
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jGestionDeConsultorio)
                                    .addComponent(jtfCodigoConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jGestionDeConsultorio)
                .addGap(42, 42, 42)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoConsultorio)
                    .addComponent(jtfCodigoConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCapacidad)
                    .addComponent(jtfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jcbApto)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCapacidad1)
                            .addComponent(jcbConsultoriosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAptoActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtfCodigoConsultorio.setText("");
        jtfUsos.setText("");
        jtfCapacidad.setText("");
        jcbApto.setSelected(false);
        consultorioActual = null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        try {
            String usos = jtfUsos.getText().trim();
            String capacidad = jtfCapacidad.getText().trim();
            boolean apto = jcbApto.isSelected();

            if (usos.isEmpty() || capacidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes completar todos los campos obligatorios", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Consultorio nuevo = new Consultorio(usos, capacidad, apto);
            ConsultorioData cd = new ConsultorioData(conexion);
            cd.guardarConsultorio(nuevo);

            consultorioActual = nuevo;
            jtfCodigoConsultorio.setText(String.valueOf(nuevo.getNroConsultorio()));

            JOptionPane.showMessageDialog(this, "Consultorio guardado correctamente");
            cargarConsultoriosActivos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el consultorio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            if (consultorioActual == null) {
                JOptionPane.showMessageDialog(this, "Primero debes buscar un consultorio", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String usos = jtfUsos.getText().trim();
            String capacidad = jtfCapacidad.getText().trim();
            boolean apto = jcbApto.isSelected();

            if (usos.isEmpty() || capacidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes completar todos los campos obligatorios", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            consultorioActual.setUsos(usos);
            consultorioActual.setEquipamiento(capacidad);
            consultorioActual.setApto(apto);

            ConsultorioData cd = new ConsultorioData(conexion);
            cd.actualizarConsultorio(consultorioActual);

            JOptionPane.showMessageDialog(this, "Consultorio actualizado correctamente");
            cargarConsultoriosActivos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar el consultorio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        try {
            if (jtfCodigoConsultorio.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa un código de consultorio para buscar", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int nro = Integer.parseInt(jtfCodigoConsultorio.getText().trim());
            ConsultorioData cd = new ConsultorioData(conexion);
            Consultorio encontrado = cd.buscarConsultorio(nro);

            if (encontrado != null) {
                consultorioActual = encontrado;
                jtfUsos.setText(encontrado.getUsos());
                jtfCapacidad.setText(encontrado.getEquipamiento());
                jcbApto.setSelected(encontrado.isApto());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún consultorio con ese número", "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el consultorio: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcbConsultoriosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConsultoriosActivosActionPerformed
        Consultorio seleccionado = (Consultorio) jcbConsultoriosActivos.getSelectedItem();
        if (seleccionado != null) {
            consultorioActual = seleccionado;
            jtfCodigoConsultorio.setText(String.valueOf(seleccionado.getNroConsultorio()));
            jtfUsos.setText(seleccionado.getUsos());
            jtfCapacidad.setText(seleccionado.getEquipamiento());
            jcbApto.setSelected(seleccionado.isApto());
        }
    }//GEN-LAST:event_jcbConsultoriosActivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCapacidad;
    private javax.swing.JLabel jCapacidad1;
    private javax.swing.JLabel jCodigoConsultorio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jGestionDeConsultorio;
    private javax.swing.JLabel jNombre;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JCheckBox jcbApto;
    private javax.swing.JComboBox<Consultorio> jcbConsultoriosActivos;
    private javax.swing.JTextField jtfCapacidad;
    private javax.swing.JTextField jtfCodigoConsultorio;
    private javax.swing.JTextField jtfUsos;
    // End of variables declaration//GEN-END:variables
}
